# Site settings
title: Experiments and experiences
email: anil at diwi dot org
description: "Randoms bits and pieces"
baseurl: "http://anil.diwi.org/exp"
twitter_username: anil_daoud
github_username:  anildaoud

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

tags_url: /tags
tags_title_prefix: "Tag: "
tags_layout: tag.html
