# Site settings
title: Experiments and experiences
email: anil at diwi dot org
description: "Randoms bits and pieces"
baseurl: "http://anil.diwi.org/exp"
twitter_username: anil_daoud
github_username:  anildaoud

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
