# Site settings
title: Experiments and experiences
email: anil at diwi dot org
description: "Random bits and pieces"
baseurl: "/exp"
url: https://anil.diwi.org
#twitter_username: anil_daoud
github_username:  anildaoud

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

tags_url: /tags
tags_title_prefix: "Tag: "
tags_layout: tag.html

future: true
